# Generated by Django 3.1.2 on 2020-10-20 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jourSemaine', models.IntegerField(default=0)),
                ('ouverture', models.DateTimeField(verbose_name='ouverture')),
                ('fermeture', models.DateTimeField(verbose_name='fermeture')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple', models.IntegerField(default=30)),
                ('special', models.IntegerField(default=45)),
                ('manip', models.IntegerField(default=55)),
            ],
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('heure', models.DateTimeField(verbose_name='heure')),
                ('horaires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendrier.horaires')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendrier.types')),
            ],
        ),
    ]
