# Generated by Django 3.1.2 on 2020-10-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_auto_20201020_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='heure',
        ),
    ]
