# Generated by Django 3.1.2 on 2020-10-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0005_auto_20201020_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='horaires',
        ),
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.DurationField(),
        ),
    ]
