# Generated by Django 3.1.2 on 2020-10-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0007_types_nom'),
    ]

    operations = [
    ]
