# Generated by Django 3.1.2 on 2020-10-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0008_auto_20201021_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='nom',
        ),
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.DurationField(choices=[(30, 'Simple'), (45, 'Spécialisé'), (55, 'Manipulation')]),
        ),
    ]
