# Generated by Django 3.1.2 on 2020-10-21 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0009_auto_20201021_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='heure',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), 'Simple'), (datetime.timedelta(seconds=3300), 'Manipulation'), (datetime.timedelta(seconds=2700), 'Spécialisé')]),
        ),
    ]
