# Generated by Django 3.1.2 on 2020-10-21 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0010_auto_20201021_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='heure',
            field=models.TimeField(verbose_name='heure'),
        ),
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=3300), 'Manipulation'), (datetime.timedelta(seconds=1800), 'Simple'), (datetime.timedelta(seconds=2700), 'Spécialisé')]),
        ),
    ]
