# Generated by Django 3.1.2 on 2020-10-22 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0015_auto_20201022_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='types',
            field=models.IntegerField(choices=[(45, 'Spécialisé'), (30, 'Simple'), (55, 'Manipulation')], default=30),
        ),
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), 'Simple'), (datetime.timedelta(seconds=2700), 'Spécialisé'), (datetime.timedelta(seconds=3300), 'Manipulation')]),
        ),
    ]
