# Generated by Django 3.1.2 on 2020-10-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('SIM', 'Rendez-vous simple'), ('SPE', 'Rendez-vous spécialiste'), ('MAN', 'Rendez-vous avec manipulation')], default='SIM', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Jour du rendez-vous', verbose_name='Jour')),
                ('start_time', models.TimeField(help_text='Heure de début du rendez-vous', verbose_name='Heure de début')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.appointmenttype')),
            ],
        ),
    ]
