# Generated by Django 3.1.2 on 2020-10-20 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('duration', models.DurationField(choices=[('Normal', datetime.timedelta(seconds=1800)), ('Specialized', datetime.timedelta(seconds=2700)), ('Handling', datetime.timedelta(seconds=3300))])),
                ('patient', models.CharField(max_length=100)),
            ],
        ),
    ]
